package forms;

import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gary Roberts 20152131 Lauriann Comrie 20161630
 */
public class ViewSales extends javax.swing.JInternalFrame {

    /**
     * Creates new form ViewSales
     */
    public ViewSales() {
        initComponents();
        loadSales();
        loadGrandTotal();
         this.getContentPane().setBackground(new Color(153,177,249,255));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        saleTable = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        salesAmount = new javax.swing.JTextField();
        totalLabel = new javax.swing.JLabel();

        setClosable(true);
        setTitle("View Sales");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Car Sale Records");

        saleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(saleTable);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel2.setText("Total Funds made:");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel3.setText("Amount of sales:");

        salesAmount.setEditable(false);

        totalLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        totalLabel.setText("Grand Total");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 933, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(399, 399, 399))))
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalLabel)
                .addGap(94, 94, 94)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(salesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(salesAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(totalLabel))
                .addGap(26, 26, 26)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private Object[] columnNames = {"SaleId", "Car Code", "Car Name", "Client Id", "First Name", "Last Name", "Quantity", "Total Paid($)", "Sale Date"};
    private Object[][] rowData = null;

    private void loadSales() {
        // TODO add your handling code here:
        DefaultTableModel tableModel = new DefaultTableModel(rowData, columnNames);
        Object[] obj;

        try {

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CarSystem", "gary", "1995");

            String query = "SELECT * FROM SALE";
            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(query);
            int num = 0;
            while (rs.next()) {
                String saleId = rs.getString("SALEID");
                String carCode = rs.getString("CARCODE");
                String carName = rs.getString("CARNAME");
                String clientId = rs.getString("CLIENTID");
                String firstName = rs.getString("FIRSTNAME");
                String lastName = rs.getString("LASTNAME");
                String quantity = rs.getString("QUANTITY");
                String totalFunds = rs.getString("TOTALFUNDS");
                String saleDate = rs.getString("SALEDATE");

                obj = new Object[]{saleId, carCode, carName, clientId, firstName, lastName, quantity, totalFunds, saleDate};
                tableModel.insertRow(num, obj);
                num++;

            }
            saleTable.setModel(tableModel);

            st.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }

        try {

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/CarSystem", "gary", "1995");

            String query = "SELECT* FROM SALE";
            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(query);
            int num = 0;
            while (rs.next()) {
                ++num;
            }
            st.close();
            String amountOfSales = Integer.toString(num);
            salesAmount.setText(amountOfSales);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "There was an error in finding \nout the number of sales");
            System.err.println(e.getMessage());
        }
    }

    private void loadGrandTotal() {
        double total = 0;
        for (int i = 0; i < saleTable.getRowCount(); i++) {
            double amount = Double.parseDouble((String) saleTable.getValueAt(i, 7));
            total += amount;
        }
        DecimalFormat dc = new DecimalFormat("0.00");
        String formattedText = "$" + dc.format(total);
        totalLabel.setText(formattedText);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable saleTable;
    private javax.swing.JTextField salesAmount;
    private javax.swing.JLabel totalLabel;
    // End of variables declaration//GEN-END:variables
}
