package Forms;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gary Roberts
 */
public class FindPatient extends javax.swing.JInternalFrame {

    private Object[] columnNames = {"PatientId", "First Name", "Last Name", "Gender", "Age", "telephone", "Street", "District", "Parish"};
    private Object[][] rowData = null;

    /**
     * Creates new form FindPatient
     */
    public FindPatient() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchKey = new javax.swing.JTextField();
        SearchButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        patientList = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        patientTable = new javax.swing.JTable();

        setClosable(true);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Find Patients");

        SearchButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        SearchButton.setText("Search Name");
        SearchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchButtonActionPerformed(evt);
            }
        });

        patientList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                patientListMousePressed(evt);
            }
        });
        jScrollPane1.setViewportView(patientList);

        patientTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(patientTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(261, Short.MAX_VALUE)
                .addComponent(searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(SearchButton)
                .addGap(418, 418, 418))
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGap(416, 416, 416)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jLabel1)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchKey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SearchButton))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(99, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchButtonActionPerformed
        // TODO add your handling code here:
        DefaultListModel list = new DefaultListModel();
        try {

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Medical", "gary", "1995");

            String query = "SELECT * FROM PATIENT WHERE FIRSTNAME like '%" + searchKey.getText() + "%'";
            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(query);

            int num = 0;
            while (rs.next()) {

                String Id = rs.getString("PATIENTID");
                String firstName = rs.getString("FIRSTNAME");
                String chosen = Id + "-" + firstName;

                list.addElement(chosen);
                num++;
            }
            patientList.setModel(list);

            st.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }
    }//GEN-LAST:event_SearchButtonActionPerformed

    private void patientListMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_patientListMousePressed
        // TODO add your handling code here:
        DefaultTableModel tableModel = new DefaultTableModel(rowData, columnNames);
        Object[] obj;
        String chosen = patientList.getSelectedValue();

        try {

            Connection conn = DriverManager.getConnection("jdbc:derby://localhost:1527/Medical", "gary", "1995");

            String query = "SELECT * FROM PATIENT WHERE FIRSTNAME like '%" + searchKey.getText() + "%'";
            Statement st = conn.createStatement();

            ResultSet rs = st.executeQuery(query);
            int num = 0;
            while (rs.next()) {
                String Id = rs.getString("PATIENTID");
                String firstName = rs.getString("FIRSTNAME");
                String lastName = rs.getString("LASTNAME");
                String gender = rs.getString("GENDER");
                String age = rs.getString("AGE");
                String telephone = rs.getString("TELEPHONE");
                String street = rs.getString("STREET");
                String district = rs.getString("DISTRICT");
                String parish = rs.getString("PARISH");

                String chosen1 = Id + "-" + firstName;
                if (chosen1.equals(chosen)) {
                    obj = new Object[]{Id, firstName, lastName, gender, age, telephone, street, district, parish};
                    tableModel.insertRow(num, obj);
                    num++;
                }
            }
            patientTable.setModel(tableModel);

            st.close();
        } catch (Exception e) {
            System.err.println("Got an exception! ");
            System.err.println(e.getMessage());
        }

    }//GEN-LAST:event_patientListMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SearchButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JList<String> patientList;
    private javax.swing.JTable patientTable;
    private javax.swing.JTextField searchKey;
    // End of variables declaration//GEN-END:variables
}
